[package]
name = "aoc_2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.2"
rayon = "1.6.1"
rand = { version = "0.8.5", features = ["small_rng"] }

[profile.release]
debug = true
